# Generated by Django 5.2.15 on 2026-06-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text="Kichik raqam yuqorida ko'rinadi.", verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name="Saytda ko'rsatilsin")),
                ('author_name', models.CharField(max_length=120, verbose_name='Muallif')),
                ('author_role', models.CharField(blank=True, help_text='masalan: Ona · Aziza R.', max_length=120, verbose_name='Roli')),
                ('author_role_uz', models.CharField(blank=True, help_text='masalan: Ona · Aziza R.', max_length=120, null=True, verbose_name='Roli')),
                ('author_role_ru', models.CharField(blank=True, help_text='masalan: Ona · Aziza R.', max_length=120, null=True, verbose_name='Roli')),
                ('author_role_en', models.CharField(blank=True, help_text='masalan: Ona · Aziza R.', max_length=120, null=True, verbose_name='Roli')),
                ('content', models.TextField(verbose_name='Fikr matni')),
                ('content_uz', models.TextField(null=True, verbose_name='Fikr matni')),
                ('content_ru', models.TextField(null=True, verbose_name='Fikr matni')),
                ('content_en', models.TextField(null=True, verbose_name='Fikr matni')),
                ('photo', models.ImageField(blank=True, upload_to='testimonials/', verbose_name='Rasm')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Baho (1–5)')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Tanlangan')),
            ],
            options={
                'verbose_name': 'Fikr',
                'verbose_name_plural': 'Fikrlar (ota-onalar)',
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
    ]
