# Generated by Django 5.2.15 on 2026-07-20 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0002_alter_testimonial_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['-is_featured', 'order', '-created_at'], 'verbose_name': 'Fikr', 'verbose_name_plural': 'Fikrlar (ota-onalar)'},
        ),
    ]
