# Generated by Django 5.2.15 on 2026-06-06 11:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('title_uz', models.CharField(max_length=200, null=True, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Sarlavha')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Sarlavha')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='Slug')),
                ('excerpt', models.CharField(blank=True, max_length=300, verbose_name='Qisqa matn')),
                ('excerpt_uz', models.CharField(blank=True, max_length=300, null=True, verbose_name='Qisqa matn')),
                ('excerpt_ru', models.CharField(blank=True, max_length=300, null=True, verbose_name='Qisqa matn')),
                ('excerpt_en', models.CharField(blank=True, max_length=300, null=True, verbose_name='Qisqa matn')),
                ('body', models.TextField(blank=True, verbose_name="To'liq matn")),
                ('body_uz', models.TextField(blank=True, null=True, verbose_name="To'liq matn")),
                ('body_ru', models.TextField(blank=True, null=True, verbose_name="To'liq matn")),
                ('body_en', models.TextField(blank=True, null=True, verbose_name="To'liq matn")),
                ('cover_image', models.ImageField(blank=True, upload_to='news/', verbose_name='Muqova rasmi')),
                ('badge', models.CharField(blank=True, help_text='masalan: Eʼlon, Yangilik, Tadbir', max_length=40, verbose_name='Belgi (tag)')),
                ('badge_uz', models.CharField(blank=True, help_text='masalan: Eʼlon, Yangilik, Tadbir', max_length=40, null=True, verbose_name='Belgi (tag)')),
                ('badge_ru', models.CharField(blank=True, help_text='masalan: Eʼlon, Yangilik, Tadbir', max_length=40, null=True, verbose_name='Belgi (tag)')),
                ('badge_en', models.CharField(blank=True, help_text='masalan: Eʼlon, Yangilik, Tadbir', max_length=40, null=True, verbose_name='Belgi (tag)')),
                ('badge_accent', models.BooleanField(default=False, verbose_name='Qizil belgi')),
                ('published_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Chop etilgan sana')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='Chop etilgan')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Tanlangan')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='SEO sarlavha')),
                ('meta_title_uz', models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO sarlavha')),
                ('meta_title_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO sarlavha')),
                ('meta_title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO sarlavha')),
                ('meta_description', models.TextField(blank=True, verbose_name='SEO tavsif')),
                ('meta_description_uz', models.TextField(blank=True, null=True, verbose_name='SEO tavsif')),
                ('meta_description_ru', models.TextField(blank=True, null=True, verbose_name='SEO tavsif')),
                ('meta_description_en', models.TextField(blank=True, null=True, verbose_name='SEO tavsif')),
            ],
            options={
                'verbose_name': 'Yangilik / eʼlon',
                'verbose_name_plural': 'Yangiliklar va eʼlonlar',
                'ordering': ['-published_at'],
            },
        ),
    ]
