# Generated by Django 5.2.15 on 2026-06-09 06:10

import apps.common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newspost_body_alter_newspost_body_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='video_file',
            field=models.FileField(blank=True, help_text='MP4/WebM. Havola berilsa, shart emas.', upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogg', 'mov']), apps.common.validators.MaxFileSizeValidator(50)], verbose_name='Video fayl'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube, Vimeo yoki embed havola.', verbose_name='Video havola'),
        ),
    ]
