# Generated by Django 5.2.15 on 2026-07-20 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newspost_video_file_newspost_video_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newspost',
            options={'ordering': ['-is_featured', '-published_at'], 'verbose_name': 'Yangilik / eʼlon', 'verbose_name_plural': 'Yangiliklar va eʼlonlar'},
        ),
    ]
