# Generated by Django 5.2.15 on 2026-06-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text="Kichik raqam yuqorida ko'rinadi.", verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name="Saytda ko'rsatilsin")),
                ('title', models.CharField(max_length=160, verbose_name='Sarlavha')),
                ('title_uz', models.CharField(max_length=160, null=True, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(max_length=160, null=True, verbose_name='Sarlavha')),
                ('title_en', models.CharField(max_length=160, null=True, verbose_name='Sarlavha')),
                ('student_name', models.CharField(blank=True, max_length=140, verbose_name="O'quvchi ismi")),
                ('description', models.CharField(blank=True, help_text='masalan: IELTS Band 7.5', max_length=200, verbose_name='Izoh')),
                ('description_uz', models.CharField(blank=True, help_text='masalan: IELTS Band 7.5', max_length=200, null=True, verbose_name='Izoh')),
                ('description_ru', models.CharField(blank=True, help_text='masalan: IELTS Band 7.5', max_length=200, null=True, verbose_name='Izoh')),
                ('description_en', models.CharField(blank=True, help_text='masalan: IELTS Band 7.5', max_length=200, null=True, verbose_name='Izoh')),
                ('badge', models.CharField(blank=True, help_text='masalan: IELTS, SAT', max_length=40, verbose_name='Belgi')),
                ('badge_uz', models.CharField(blank=True, help_text='masalan: IELTS, SAT', max_length=40, null=True, verbose_name='Belgi')),
                ('badge_ru', models.CharField(blank=True, help_text='masalan: IELTS, SAT', max_length=40, null=True, verbose_name='Belgi')),
                ('badge_en', models.CharField(blank=True, help_text='masalan: IELTS, SAT', max_length=40, null=True, verbose_name='Belgi')),
                ('badge_accent', models.BooleanField(default=False, verbose_name='Qizil belgi')),
                ('image', models.ImageField(blank=True, upload_to='certificates/', verbose_name='Rasm')),
                ('pdf_file', models.FileField(blank=True, upload_to='certificates/pdf/', verbose_name='PDF fayl')),
                ('external_url', models.URLField(blank=True, verbose_name='Tashqi havola')),
            ],
            options={
                'verbose_name': 'Sertifikat',
                'verbose_name_plural': 'Sertifikatlar',
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
    ]
