# Generated by Django 5.2.15 on 2026-06-06 12:55

import apps.common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='image',
            field=models.ImageField(blank=True, upload_to='certificates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), apps.common.validators.MaxFileSizeValidator(5)], verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to='certificates/pdf/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), apps.common.validators.MaxFileSizeValidator(10)], verbose_name='PDF fayl'),
        ),
    ]
