# Generated by Django 5.2.15 on 2026-07-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_alter_certificate_image_alter_certificate_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='issued_on',
            field=models.DateField(blank=True, help_text='PDF havoladan avtomatik aniqlanadi (topilsa).', null=True, verbose_name='Sertifikat olingan sanasi'),
        ),
    ]
