# Generated by Django 5.2.15 on 2026-07-11 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_certificate_issued_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='badge_en',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='badge_ru',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='badge_uz',
        ),
    ]
