# Generated by Django 5.2.15 on 2026-06-06 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text="Kichik raqam yuqorida ko'rinadi.", verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name="Saytda ko'rsatilsin")),
                ('name', models.CharField(max_length=80, verbose_name='Nomi')),
                ('name_uz', models.CharField(max_length=80, null=True, verbose_name='Nomi')),
                ('name_ru', models.CharField(max_length=80, null=True, verbose_name='Nomi')),
                ('name_en', models.CharField(max_length=80, null=True, verbose_name='Nomi')),
                ('slug', models.SlugField(max_length=90, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Kurs turkumi',
                'verbose_name_plural': 'Kurs turkumlari',
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text="Kichik raqam yuqorida ko'rinadi.", verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name="Saytda ko'rsatilsin")),
                ('name', models.CharField(max_length=140, verbose_name='Nomi')),
                ('name_uz', models.CharField(max_length=140, null=True, verbose_name='Nomi')),
                ('name_ru', models.CharField(max_length=140, null=True, verbose_name='Nomi')),
                ('name_en', models.CharField(max_length=140, null=True, verbose_name='Nomi')),
                ('slug', models.SlugField(max_length=160, unique=True, verbose_name='Slug')),
                ('short_description', models.CharField(blank=True, max_length=255, verbose_name='Qisqa tavsif')),
                ('short_description_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='Qisqa tavsif')),
                ('short_description_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Qisqa tavsif')),
                ('short_description_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Qisqa tavsif')),
                ('description', models.TextField(blank=True, verbose_name="To'liq tavsif")),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name="To'liq tavsif")),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name="To'liq tavsif")),
                ('description_en', models.TextField(blank=True, null=True, verbose_name="To'liq tavsif")),
                ('duration_text', models.CharField(blank=True, help_text='masalan: 6 oy', max_length=60, verbose_name='Davomiyligi')),
                ('duration_text_uz', models.CharField(blank=True, help_text='masalan: 6 oy', max_length=60, null=True, verbose_name='Davomiyligi')),
                ('duration_text_ru', models.CharField(blank=True, help_text='masalan: 6 oy', max_length=60, null=True, verbose_name='Davomiyligi')),
                ('duration_text_en', models.CharField(blank=True, help_text='masalan: 6 oy', max_length=60, null=True, verbose_name='Davomiyligi')),
                ('group_size', models.CharField(blank=True, help_text='masalan: 6–10', max_length=40, verbose_name='Guruh hajmi')),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Narx')),
                ('price_note', models.CharField(blank=True, help_text="masalan: so'm/oy", max_length=40, verbose_name='Narx izohi')),
                ('price_note_uz', models.CharField(blank=True, help_text="masalan: so'm/oy", max_length=40, null=True, verbose_name='Narx izohi')),
                ('price_note_ru', models.CharField(blank=True, help_text="masalan: so'm/oy", max_length=40, null=True, verbose_name='Narx izohi')),
                ('price_note_en', models.CharField(blank=True, help_text="masalan: so'm/oy", max_length=40, null=True, verbose_name='Narx izohi')),
                ('is_price_visible', models.BooleanField(default=True, verbose_name="Narx ko'rsatilsin")),
                ('icon', models.CharField(choices=[('cap', 'Bitiruv shapkasi'), ('users', 'Foydalanuvchi'), ('method', 'Metodika'), ('group', 'Guruh'), ('shield', 'Qalqon (kafolat)'), ('book', 'Kitob / til'), ('calc', 'Hisob / matematika'), ('code', 'Kod / IT'), ('chart', 'Grafik'), ('clock', 'Soat'), ('star', 'Yulduz'), ('location', 'Manzil'), ('language', 'Til (globus)')], default='book', max_length=20, verbose_name='Ikonka')),
                ('image', models.ImageField(blank=True, upload_to='courses/', verbose_name='Rasm')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Top kurs (qizil belgi)')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='SEO sarlavha')),
                ('meta_title_uz', models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO sarlavha')),
                ('meta_title_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO sarlavha')),
                ('meta_title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO sarlavha')),
                ('meta_description', models.TextField(blank=True, verbose_name='SEO tavsif')),
                ('meta_description_uz', models.TextField(blank=True, null=True, verbose_name='SEO tavsif')),
                ('meta_description_ru', models.TextField(blank=True, null=True, verbose_name='SEO tavsif')),
                ('meta_description_en', models.TextField(blank=True, null=True, verbose_name='SEO tavsif')),
                ('og_image', models.ImageField(blank=True, upload_to='courses/og/', verbose_name='OG rasm')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.coursecategory', verbose_name='Turkum')),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
    ]
