# Generated by Django 5.2.15 on 2026-06-06 12:55

import apps.common.validators
import django.core.validators
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name="To'liq tavsif"),
        ),
        migrations.AlterField(
            model_name='course',
            name='description_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name="To'liq tavsif"),
        ),
        migrations.AlterField(
            model_name='course',
            name='description_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name="To'liq tavsif"),
        ),
        migrations.AlterField(
            model_name='course',
            name='description_uz',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name="To'liq tavsif"),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, upload_to='courses/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), apps.common.validators.MaxFileSizeValidator(5)], verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='course',
            name='og_image',
            field=models.ImageField(blank=True, upload_to='courses/og/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), apps.common.validators.MaxFileSizeValidator(5)], verbose_name='OG rasm'),
        ),
    ]
