# Generated by Django 5.2.15 on 2026-06-09 06:10

import apps.common.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_description_alter_course_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video_file',
            field=models.FileField(blank=True, help_text='MP4/WebM. Havola berilsa, shart emas.', upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogg', 'mov']), apps.common.validators.MaxFileSizeValidator(50)], verbose_name='Video fayl'),
        ),
        migrations.AddField(
            model_name='course',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube, Vimeo yoki embed havola.', verbose_name='Video havola'),
        ),
        migrations.CreateModel(
            name='CourseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text="Kichik raqam yuqorida ko'rinadi.", verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name="Saytda ko'rsatilsin")),
                ('image', models.ImageField(upload_to='courses/gallery/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), apps.common.validators.MaxFileSizeValidator(5)], verbose_name='Rasm')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Izoh')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='courses.course', verbose_name='Kurs')),
            ],
            options={
                'verbose_name': 'Kurs rasmi',
                'verbose_name_plural': 'Kurs rasmlari',
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
    ]
