# Generated by Django 5.2.15 on 2026-06-06 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_alter_course_description_alter_course_description_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('full_name', models.CharField(max_length=140, verbose_name='Ism familiya')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('message', models.TextField(blank=True, verbose_name='Izoh')),
                ('source', models.CharField(blank=True, help_text='UTM yoki referrer (avtomatik toʻldiriladi).', max_length=255, verbose_name='Manba')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('contacted', 'Bogʻlanildi'), ('enrolled', 'Oʻquvchi boʻldi'), ('rejected', 'Rad etildi')], db_index=True, default='new', max_length=20, verbose_name='Holat')),
                ('is_notified', models.BooleanField(default=False, verbose_name='Telegramga yuborildi')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='courses.course', verbose_name='Kurs')),
            ],
            options={
                'verbose_name': 'Ariza',
                'verbose_name_plural': 'Arizalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
