# Generated by Django 5.2.15 on 2026-07-04 11:06

import apps.common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_create_cache_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text="Kichik raqam yuqorida ko'rinadi.", verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name="Saytda ko'rsatilsin")),
                ('name', models.CharField(max_length=80, verbose_name='Nomi')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='Slug')),
                ('icon', models.CharField(blank=True, help_text='Material Symbols nomi (masalan: public). Rasm boʻlmaganda ishlatiladi.', max_length=48, verbose_name='Ikonka')),
                ('image', models.ImageField(blank=True, upload_to='crm/sources/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), apps.common.validators.MaxFileSizeValidator(5)], verbose_name='Rasm (hisobot uchun)')),
                ('color', models.CharField(blank=True, help_text='#RRGGBB. Boʻsh boʻlsa asosiy rang ishlatiladi.', max_length=7, verbose_name='Rang')),
                ('is_protected', models.BooleanField(default=False, editable=False, verbose_name='Himoyalangan')),
            ],
            options={
                'verbose_name': 'Manba',
                'verbose_name_plural': 'Manbalar',
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
    ]
