# Generated by Django 5.2.15 on 2026-06-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='telegram_group_url',
            field=models.URLField(blank=True, verbose_name='Telegram guruh'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='telegram_url',
            field=models.URLField(blank=True, verbose_name='Telegram kanal'),
        ),
    ]
