# Generated by Django 5.2.15 on 2026-06-06 12:55

import apps.common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0002_siteconfig_telegram_group_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='favicon',
            field=models.ImageField(blank=True, upload_to='branding/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), apps.common.validators.MaxFileSizeValidator(5)], verbose_name='Favicon'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='logo',
            field=models.ImageField(blank=True, help_text="Bo'sh qoldirilsa, standart logo ishlatiladi.", upload_to='branding/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), apps.common.validators.MaxFileSizeValidator(5)], verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='og_image',
            field=models.ImageField(blank=True, upload_to='seo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), apps.common.validators.MaxFileSizeValidator(5)], verbose_name='OG rasm (ulashish)'),
        ),
    ]
