# Generated by Django 5.2.15 on 2026-06-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0003_alter_siteconfig_favicon_alter_siteconfig_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text="Kichik raqam yuqorida ko'rinadi.", verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name="Saytda ko'rsatilsin")),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('telegram', 'Telegram'), ('telegram_group', 'Telegram guruh'), ('youtube', 'YouTube'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('twitter', 'X (Twitter)'), ('linkedin', 'LinkedIn'), ('whatsapp', 'WhatsApp'), ('website', 'Veb-sayt')], max_length=20, verbose_name='Platforma')),
                ('label', models.CharField(blank=True, help_text='Boʻsh qoldirilsa, platforma nomi ishlatiladi.', max_length=60, verbose_name='Nomi (ixtiyoriy)')),
                ('url', models.URLField(verbose_name='Havola')),
            ],
            options={
                'verbose_name': 'Ijtimoiy tarmoq',
                'verbose_name_plural': 'Ijtimoiy tarmoqlar',
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
    ]
