# Generated by Django 5.2.15 on 2026-06-09 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0005_seed_social_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='telegram_group_url',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='telegram_url',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='tiktok_url',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='youtube_url',
        ),
    ]
