# Generated by Django 5.2.15 on 2026-06-14 21:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0006_remove_siteconfig_facebook_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('name', models.CharField(blank=True, help_text='Kimligini eslatuvchi nom (masalan: Direktor). Ixtiyoriy.', max_length=120, verbose_name='Nomi')),
                ('chat_id', models.CharField(help_text='Raqamli chat ID (masalan: 123456789). Foydalanuvchi botga /start yozgach, @userinfobot orqali bilib olish mumkin.', max_length=64, validators=[django.core.validators.RegexValidator(message='Chat ID raqam (masalan: 123456789 yoki -1001234567890) yoki @username koʻrinishida boʻlishi kerak.', regex='^(-?\\d+|@[A-Za-z0-9_]{4,})$')], verbose_name='Chat ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Belgilanmasa, bu adminga arizalar yuborilmaydi.', verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Telegram qabul qiluvchi',
                'verbose_name_plural': 'Telegram qabul qiluvchilar',
                'ordering': ['name', 'chat_id'],
            },
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='telegram_bot_token',
            field=models.CharField(blank=True, help_text='@BotFather bergan token. Boʻsh qoldirilsa, serverdagi .env qiymati ishlatiladi.', max_length=128, verbose_name='Telegram bot tokeni'),
        ),
    ]
