# Generated by Django 5.2.16 on 2026-07-10 07:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0007_telegramrecipient_siteconfig_telegram_bot_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='ga4_measurement_id',
            field=models.CharField(blank=True, help_text='G-XXXXXXX', max_length=40, validators=[django.core.validators.RegexValidator(message='Google Analytics ID G-XXXXXXX (yoki UA-XXXX-Y) koʻrinishida boʻlishi kerak.', regex='^(G-[A-Z0-9]{4,20}|UA-\\d{4,10}-\\d{1,4})$')], verbose_name='Google Analytics 4 ID'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='yandex_metrica_id',
            field=models.CharField(blank=True, max_length=40, validators=[django.core.validators.RegexValidator(message='Yandex Metrica ID faqat raqamlardan iborat boʻlishi kerak (masalan: 12345678).', regex='^\\d{4,12}$')], verbose_name='Yandex Metrica ID'),
        ),
    ]
