# Generated by Django 5.2.15 on 2026-07-20 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0008_alter_siteconfig_ga4_measurement_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='yandex_maps_embed',
        ),
    ]
