# Generated by Django 5.2.15 on 2026-06-06 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text="Kichik raqam yuqorida ko'rinadi.", verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name="Saytda ko'rsatilsin")),
                ('title', models.CharField(max_length=140, verbose_name='Albom nomi')),
                ('title_uz', models.CharField(max_length=140, null=True, verbose_name='Albom nomi')),
                ('title_ru', models.CharField(max_length=140, null=True, verbose_name='Albom nomi')),
                ('title_en', models.CharField(max_length=140, null=True, verbose_name='Albom nomi')),
                ('slug', models.SlugField(max_length=160, unique=True, verbose_name='Slug')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Tavsif')),
                ('description_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tavsif')),
                ('description_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tavsif')),
                ('description_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tavsif')),
                ('cover_image', models.ImageField(blank=True, upload_to='gallery/covers/', verbose_name='Muqova rasmi')),
            ],
            options={
                'verbose_name': 'Galereya albomi',
                'verbose_name_plural': 'Galereya albomlari',
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text="Kichik raqam yuqorida ko'rinadi.", verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name="Saytda ko'rsatilsin")),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Rasm')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Izoh')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='ALT matn (SEO)')),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gallery.galleryalbum', verbose_name='Albom')),
            ],
            options={
                'verbose_name': 'Galereya rasmi',
                'verbose_name_plural': 'Galereya rasmlari',
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
    ]
