# Generated by Django 5.2.15 on 2026-06-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_galleryalbum_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='alt_text_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ALT matn (SEO)'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='alt_text_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ALT matn (SEO)'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='alt_text_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ALT matn (SEO)'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='caption_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Izoh'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='caption_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Izoh'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='caption_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Izoh'),
        ),
    ]
