# Generated by Django 5.2.15 on 2026-06-09 06:10

import apps.common.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_galleryimage_alt_text_en_galleryimage_alt_text_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(blank=True, help_text='YouTube, Vimeo yoki embed havola.', verbose_name='Video havola')),
                ('video_file', models.FileField(blank=True, help_text='MP4/WebM. Havola berilsa, shart emas.', upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogg', 'mov']), apps.common.validators.MaxFileSizeValidator(50)], verbose_name='Video fayl')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text="Kichik raqam yuqorida ko'rinadi.", verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name="Saytda ko'rsatilsin")),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Sarlavha')),
                ('title_uz', models.CharField(blank=True, max_length=200, null=True, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Sarlavha')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Sarlavha')),
                ('thumbnail', models.ImageField(blank=True, help_text='Ixtiyoriy — yuklangan video uchun muqova.', upload_to='gallery/video_covers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), apps.common.validators.MaxFileSizeValidator(5)], verbose_name='Muqova rasmi')),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='gallery.galleryalbum', verbose_name='Albom')),
            ],
            options={
                'verbose_name': 'Galereya videosi',
                'verbose_name_plural': 'Galereya videolari',
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
    ]
