# Generated by Django 5.2.15 on 2026-06-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text="Kichik raqam yuqorida ko'rinadi.", verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name="Saytda ko'rsatilsin")),
                ('full_name', models.CharField(max_length=140, verbose_name='F.I.Sh.')),
                ('slug', models.SlugField(max_length=160, unique=True, verbose_name='Slug')),
                ('photo', models.ImageField(blank=True, upload_to='teachers/', verbose_name='Rasm')),
                ('position', models.CharField(blank=True, max_length=160, verbose_name="Lavozim / yo'nalish")),
                ('position_uz', models.CharField(blank=True, max_length=160, null=True, verbose_name="Lavozim / yo'nalish")),
                ('position_ru', models.CharField(blank=True, max_length=160, null=True, verbose_name="Lavozim / yo'nalish")),
                ('position_en', models.CharField(blank=True, max_length=160, null=True, verbose_name="Lavozim / yo'nalish")),
                ('bio', models.TextField(blank=True, verbose_name='Bio / tavsif')),
                ('bio_uz', models.TextField(blank=True, null=True, verbose_name='Bio / tavsif')),
                ('bio_ru', models.TextField(blank=True, null=True, verbose_name='Bio / tavsif')),
                ('bio_en', models.TextField(blank=True, null=True, verbose_name='Bio / tavsif')),
                ('subjects', models.CharField(blank=True, max_length=200, verbose_name='Fanlar')),
                ('subjects_uz', models.CharField(blank=True, max_length=200, null=True, verbose_name='Fanlar')),
                ('subjects_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Fanlar')),
                ('subjects_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Fanlar')),
                ('experience_years', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tajriba (yil)')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('telegram_url', models.URLField(blank=True, verbose_name='Telegram')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='SEO sarlavha')),
                ('meta_title_uz', models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO sarlavha')),
                ('meta_title_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO sarlavha')),
                ('meta_title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO sarlavha')),
                ('meta_description', models.TextField(blank=True, verbose_name='SEO tavsif')),
                ('meta_description_uz', models.TextField(blank=True, null=True, verbose_name='SEO tavsif')),
                ('meta_description_ru', models.TextField(blank=True, null=True, verbose_name='SEO tavsif')),
                ('meta_description_en', models.TextField(blank=True, null=True, verbose_name='SEO tavsif')),
            ],
            options={
                'verbose_name': "O'qituvchi",
                'verbose_name_plural': "O'qituvchilar",
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
    ]
