# Generated by Django 5.2.15 on 2026-06-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text="Kichik raqam yuqorida ko'rinadi.", verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name="Saytda ko'rsatilsin")),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('title_uz', models.CharField(max_length=200, null=True, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Sarlavha')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Sarlavha')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='Kichik sarlavha')),
                ('subtitle_uz', models.CharField(blank=True, max_length=200, null=True, verbose_name='Kichik sarlavha')),
                ('subtitle_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Kichik sarlavha')),
                ('subtitle_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Kichik sarlavha')),
                ('body', models.TextField(blank=True, verbose_name='Matn')),
                ('body_uz', models.TextField(blank=True, null=True, verbose_name='Matn')),
                ('body_ru', models.TextField(blank=True, null=True, verbose_name='Matn')),
                ('body_en', models.TextField(blank=True, null=True, verbose_name='Matn')),
                ('image', models.ImageField(blank=True, upload_to='about/', verbose_name='Rasm')),
            ],
            options={
                'verbose_name': "Biz haqimizda bo'limi",
                'verbose_name_plural': "Biz haqimizda bo'limi",
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text="Kichik raqam yuqorida ko'rinadi.", verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name="Saytda ko'rsatilsin")),
                ('number', models.PositiveIntegerField(default=0, verbose_name='Raqam')),
                ('suffix', models.CharField(blank=True, help_text='+, %, k …', max_length=8, verbose_name='Belgi')),
                ('label', models.CharField(max_length=80, verbose_name='Izoh')),
                ('label_uz', models.CharField(max_length=80, null=True, verbose_name='Izoh')),
                ('label_ru', models.CharField(max_length=80, null=True, verbose_name='Izoh')),
                ('label_en', models.CharField(max_length=80, null=True, verbose_name='Izoh')),
                ('accent', models.BooleanField(default=False, verbose_name='Qizil rang bilan')),
            ],
            options={
                'verbose_name': 'Statistika raqami',
                'verbose_name_plural': 'Statistika raqamlari',
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WhyUsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text="Kichik raqam yuqorida ko'rinadi.", verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name="Saytda ko'rsatilsin")),
                ('title', models.CharField(max_length=120, verbose_name='Sarlavha')),
                ('title_uz', models.CharField(max_length=120, null=True, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(max_length=120, null=True, verbose_name='Sarlavha')),
                ('title_en', models.CharField(max_length=120, null=True, verbose_name='Sarlavha')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('icon', models.CharField(choices=[('cap', 'Bitiruv shapkasi'), ('users', 'Foydalanuvchi'), ('method', 'Metodika'), ('group', 'Guruh'), ('shield', 'Qalqon (kafolat)'), ('book', 'Kitob / til'), ('calc', 'Hisob / matematika'), ('code', 'Kod / IT'), ('chart', 'Grafik'), ('clock', 'Soat'), ('star', 'Yulduz'), ('location', 'Manzil'), ('language', 'Til (globus)')], default='cap', max_length=20, verbose_name='Ikonka')),
                ('accent', models.BooleanField(default=False, verbose_name='Qizil ikonka')),
            ],
            options={
                'verbose_name': 'Nega biz — karta',
                'verbose_name_plural': 'Nega biz — kartalar',
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
    ]
