# Generated by Django 5.2.15 on 2026-06-09 06:10

import apps.common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_seed_sitecopy_translations'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(blank=True, help_text='YouTube, Vimeo yoki embed havola.', verbose_name='Video havola')),
                ('video_file', models.FileField(blank=True, help_text='MP4/WebM. Havola berilsa, shart emas.', upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogg', 'mov']), apps.common.validators.MaxFileSizeValidator(50)], verbose_name='Video fayl')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='Yoqilgan')),
                ('title', models.CharField(blank=True, max_length=160, verbose_name='Sarlavha')),
                ('title_uz', models.CharField(blank=True, max_length=160, null=True, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(blank=True, max_length=160, null=True, verbose_name='Sarlavha')),
                ('title_en', models.CharField(blank=True, max_length=160, null=True, verbose_name='Sarlavha')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Kichik matn')),
                ('subtitle_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kichik matn')),
                ('subtitle_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kichik matn')),
                ('subtitle_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kichik matn')),
            ],
            options={
                'verbose_name': 'Bosh sahifa videosi',
                'verbose_name_plural': 'Bosh sahifa videosi',
            },
        ),
    ]
