# Generated by Django 5.2.15 on 2026-07-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_homevideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='metric1_value',
            field=models.CharField(default='IELTS 7.5', help_text="Chap yuqoridagi yorliq, masalan «IELTS 7.5» ('oʻrtacha' izohi bilan).", max_length=40, verbose_name='1-yorliq — qiymat'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='metric2_value',
            field=models.CharField(default='100+', help_text="«Bu oy … yangi oʻquvchi» yorlig'idagi raqam, masalan «100+».", max_length=20, verbose_name='2-yorliq — qiymat'),
        ),
    ]
