# Generated by Django 5.2.15 on 2026-07-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_herosection_metric1_value_herosection_metric2_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text="Kichik raqam yuqorida ko'rinadi.", verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name="Saytda ko'rsatilsin")),
                ('name', models.CharField(max_length=80, verbose_name='Nomi')),
                ('name_uz', models.CharField(max_length=80, null=True, verbose_name='Nomi')),
                ('name_ru', models.CharField(max_length=80, null=True, verbose_name='Nomi')),
                ('name_en', models.CharField(max_length=80, null=True, verbose_name='Nomi')),
                ('website_url', models.URLField(blank=True, verbose_name='Veb-sayt (ixtiyoriy)')),
            ],
            options={
                'verbose_name': 'Hamkor',
                'verbose_name_plural': 'Hamkorlar',
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
    ]
