# Generated by Django 5.2.15 on 2026-07-11 14:48

import apps.common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_seed_partners'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='image',
            field=models.ImageField(blank=True, help_text='Hero blokidagi katta rasm/poster.', upload_to='hero/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), apps.common.validators.MaxFileSizeValidator(5)], verbose_name='Rasm'),
        ),
    ]
