# Generated by Django 5.2.15 on 2026-06-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=512, verbose_name='Manzil')),
                ('method', models.CharField(max_length=8, verbose_name='Metod')),
                ('referrer', models.CharField(blank=True, max_length=512, verbose_name='Yoʻnaltiruvchi')),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='IP manzil')),
                ('user_agent', models.TextField(blank=True, verbose_name='Brauzer maʼlumoti')),
                ('device_type', models.CharField(choices=[('mobile', 'Telefon'), ('tablet', 'Planshet'), ('desktop', 'Kompyuter'), ('bot', 'Bot'), ('other', 'Boshqa')], db_index=True, default='other', max_length=10, verbose_name='Qurilma turi')),
                ('browser', models.CharField(blank=True, max_length=80, verbose_name='Brauzer')),
                ('os', models.CharField(blank=True, max_length=80, verbose_name='Operatsion tizim')),
                ('language', models.CharField(blank=True, max_length=8, verbose_name='Til')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Vaqti')),
            ],
            options={
                'verbose_name': 'Tashrif',
                'verbose_name_plural': 'Tashriflar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at', 'device_type'], name='analytics_v_created_33d279_idx'), models.Index(fields=['created_at', 'path'], name='analytics_v_created_104496_idx')],
            },
        ),
    ]
