# Generated by Django 5.2.15 on 2026-06-09 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitlog',
            name='country',
            field=models.CharField(blank=True, db_index=True, max_length=80, verbose_name='Davlat'),
        ),
        migrations.AddField(
            model_name='visitlog',
            name='country_code',
            field=models.CharField(blank=True, max_length=2, verbose_name='Davlat kodi'),
        ),
    ]
