# -*- coding: utf-8 -*-
"""Parse _draft_translations.txt, apply hand corrections, and write
_extra_translations.py (PROJECT_RU/PROJECT_EN + UNFOLD_UZ/UNFOLD_RU dicts) for
the build scripts to merge. One-off authoring helper.
"""
import os
import re

BASE = os.path.dirname(os.path.abspath(__file__))

_APOS = {"ʻ": "'", "ʼ": "'", "‘": "'", "’": "'", "′": "'", "`": "'"}


def norm(s):
    for k, v in _APOS.items():
        s = s.replace(k, v)
    return s


# --- Corrections keyed by ASCII-normalized source (override bad MT) ----------
CORR_RU = {
    "Bogʻlanildi": "Связались",
    "Bogʻlanish": "Контакты",
    "Davlat": "Страна",
    "Davlat kodi": "Код страны",
    "Boʻlim": "Раздел",
    "Soni": "Количество",
    "Oʻquvchi boʻldi": "Стал учеником",
    "Yoʻnaltiruvchi": "Источник перехода",
    "oʻrtacha": "в среднем",
    "yangi oʻquvchi": "новых учеников",
    "Yangilik / eʼlon": "Новость / объявление",
    "Fikrlar — sarlavha": "Отзывы — заголовок",
    "Top manbalar": "Топ источников",
    "Top sahifalar": "Топ страниц",
    "Footer": "Подвал",
    "Footer — pastki matn": "Подвал — нижний текст",
    "Kontakt — sarlavha": "Контакт — заголовок",
    "Oyna — sarlavha": "Окно — заголовок",
    "Sarlavha — boshi": "Заголовок — начало",
    "Sarlavha — oxiri": "Заголовок — конец",
    "Sayt kontenti": "Содержимое сайта",
    "Brauzer maʼlumoti": "Данные браузера",
}
CORR_EN = {
    "Bogʻlanildi": "Contacted",
    "Bogʻlanish": "Contact",
    "Davlat": "Country",
    "Davlat kodi": "Country code",
    "Boʻlim": "Section",
    "Soni": "Count",
    "Oʻquvchi boʻldi": "Enrolled",
    "Yoʻnaltiruvchi": "Referrer",
    "oʻrtacha": "average",
    "yangi oʻquvchi": "new students",
    "Yangilik / eʼlon": "News / announcement",
    "Fikrlar — sarlavha": "Reviews — title",
    "Top manbalar": "Top sources",
    "Top sahifalar": "Top pages",
    "Footer — pastki matn": "Footer — bottom text",
    "Sarlavha — boshi": "Title — beginning",
    "Sarlavha — oxiri": "Title — end",
    "Arizalar holati boʻyicha": "By application status",
    "Sayt kontenti": "Site content",
    "Brauzer maʼlumoti": "User agent",
}
CORR_UF_UZ = {
    "Clear": "Tozalash",
    "General": "Umumiy",
    "Light": "Yorugʻ",
    "Run": "Bajarish",
    "Save and continue editing": "Saqlash va tahrirni davom ettirish",
    "False": "Notoʻgʻri",
    "True": "Toʻgʻri",
    "View": "Koʻrish",
    "Navigate": "Oʻtish",
}
CORR_UF_RU = {
    "Run": "Выполнить",
    "Light": "Светлая",
    "Dark": "Тёмная",
    "System": "Системная",
    "General": "Общее",
    "Record picture": "Изображение записи",
}


def parse_sections(path):
    text = open(path, encoding="utf-8").read()
    sections, cur, buf = {}, None, []
    for line in text.splitlines():
        m = re.match(r"#\s*=====\s*(.+?)\s*=====", line)
        if m:
            if cur:
                sections[cur] = buf
            cur, buf = m.group(1), []
        elif cur and re.match(r"\s*['\"]", line):
            buf.append(line.rstrip())
    if cur:
        sections[cur] = buf
    return sections


def to_dict(lines):
    ns = {}
    exec("d = {\n" + "\n".join(lines) + "\n}", ns)
    return ns["d"]


def find(sections, needle):
    for k in sections:
        if needle in k:
            return sections[k]
    raise KeyError(needle)


def apply_corr(d, corr):
    corr_n = {norm(k): v for k, v in corr.items()}
    for key in list(d):
        nk = norm(key)
        if nk in corr_n:
            d[key] = corr_n[nk]
    return d


def dump(name, d, f):
    f.write(f"{name} = {{\n")
    for k, v in d.items():
        f.write(f"    {k!r}: {v!r},\n")
    f.write("}\n\n")


def main():
    s = parse_sections(os.path.join(BASE, "_draft_translations.txt"))
    project_ru = apply_corr(to_dict(find(s, "PROJECT -> RU")), CORR_RU)
    project_en = apply_corr(to_dict(find(s, "PROJECT -> EN")), CORR_EN)
    unfold_uz = apply_corr(to_dict(find(s, "UNFOLD -> UZ")), CORR_UF_UZ)
    unfold_ru = apply_corr(to_dict(find(s, "UNFOLD -> RU")), CORR_UF_RU)

    out = os.path.join(BASE, "_extra_translations.py")
    with open(out, "w", encoding="utf-8") as f:
        f.write("# -*- coding: utf-8 -*-\n")
        f.write('"""Auto-drafted + hand-corrected admin translations.\n')
        f.write("Generated by _make_extra.py from _draft_translations.txt.\n")
        f.write('Merged by _build_catalogs.py (ru/en) and _build_uz_admin.py (uz)."""\n\n')
        dump("PROJECT_RU", project_ru, f)
        dump("PROJECT_EN", project_en, f)
        dump("UNFOLD_UZ", unfold_uz, f)
        dump("UNFOLD_RU", unfold_ru, f)
    print(f"Wrote {out}: project_ru={len(project_ru)} project_en={len(project_en)} "
          f"unfold_uz={len(unfold_uz)} unfold_ru={len(unfold_ru)}")


if __name__ == "__main__":
    main()
